name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.0
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.0'
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        conda activate base
    - name: Lint with flake8
      run: |
        conda install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
